/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct read_args {
	char *filename;
	int pos;
	int cantBytes;
};
typedef struct read_args read_args;

struct write_args {
	char *filename;
	int cantBytes;
	char *buffer;
};
typedef struct write_args write_args;

struct read_return {
	char *buffer_read;
	int cant_asked;
	int cant_read;
};
typedef struct read_return read_return;

#define FTP_SERVER 0x20000000001
#define FTP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define leer 1
extern  read_return * leer_1(void *, CLIENT *);
extern  read_return * leer_1_svc(void *, struct svc_req *);
#define escribir 2
extern  int * escribir_1(void *, CLIENT *);
extern  int * escribir_1_svc(void *, struct svc_req *);
extern int ftp_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leer 1
extern  read_return * leer_1();
extern  read_return * leer_1_svc();
#define escribir 2
extern  int * escribir_1();
extern  int * escribir_1_svc();
extern int ftp_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_read_args (XDR *, read_args*);
extern  bool_t xdr_write_args (XDR *, write_args*);
extern  bool_t xdr_read_return (XDR *, read_return*);

#else /* K&R C */
extern bool_t xdr_read_args ();
extern bool_t xdr_write_args ();
extern bool_t xdr_read_return ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
