/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct read_args {
	char *name;
	int pos;
	int cantBytes;
};
typedef struct read_args read_args;

struct read_result {
	char *buffer_read;
	int cant_asked;
	int cant_read;
};
typedef struct read_result read_result;

struct write_args {
	char *name;
	int cant;
	char *buffer;
};
typedef struct write_args write_args;

#define SRV_FTP 555555555
#define FTP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define leer 1
extern  read_result * leer_1(read_args *, CLIENT *);
extern  read_result * leer_1_svc(read_args *, struct svc_req *);
#define escribir 2
extern  int * escribir_1(write_args *, CLIENT *);
extern  int * escribir_1_svc(write_args *, struct svc_req *);
extern int srv_ftp_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leer 1
extern  read_result * leer_1();
extern  read_result * leer_1_svc();
#define escribir 2
extern  int * escribir_1();
extern  int * escribir_1_svc();
extern int srv_ftp_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_read_args (XDR *, read_args*);
extern  bool_t xdr_read_result (XDR *, read_result*);
extern  bool_t xdr_write_args (XDR *, write_args*);

#else /* K&R C */
extern bool_t xdr_read_args ();
extern bool_t xdr_read_result ();
extern bool_t xdr_write_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
