/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FTP_H_RPCGEN
#define _FTP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *file;

typedef char *buffer;

struct read_args {
	file filename;
	int pos;
	int cantBytes;
};
typedef struct read_args read_args;

struct write_args {
	file filename;
	int cantBytes;
	buffer buffer_write;
};
typedef struct write_args write_args;

struct read_return {
	buffer buffer_read;
	int cant_asked;
	int cant_read;
};
typedef struct read_return read_return;

#define FTP_SERVER 55555556
#define FTP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define leer 1
extern  read_return * leer_1(read_args *, CLIENT *);
extern  read_return * leer_1_svc(read_args *, struct svc_req *);
#define escribir 2
extern  int * escribir_1(write_args *, CLIENT *);
extern  int * escribir_1_svc(write_args *, struct svc_req *);
extern int ftp_server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define leer 1
extern  read_return * leer_1();
extern  read_return * leer_1_svc();
#define escribir 2
extern  int * escribir_1();
extern  int * escribir_1_svc();
extern int ftp_server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_file (XDR *, file*);
extern  bool_t xdr_buffer (XDR *, buffer*);
extern  bool_t xdr_read_args (XDR *, read_args*);
extern  bool_t xdr_write_args (XDR *, write_args*);
extern  bool_t xdr_read_return (XDR *, read_return*);

#else /* K&R C */
extern bool_t xdr_file ();
extern bool_t xdr_buffer ();
extern bool_t xdr_read_args ();
extern bool_t xdr_write_args ();
extern bool_t xdr_read_return ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FTP_H_RPCGEN */
