/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"
#include <stdio.h>
#define DATA_SIZE UINT_MAX
#define PKG_SIZE 1024






void
read_ftp_server_1(char *host, char * fname, int requestedBytes, int pos)
{
	
	CLIENT *clnt;
	ftp_file  *result_1;
	ftp_req  read_1_arg;
	int cantRead = 0;
	

#ifndef	DEBUG
	clnt = clnt_create (host, FTP_PROG, FTP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBcant_leidoscant_leidosUG */
	read_1_arg.name = fname;
	read_1_arg.pos = pos;
	u_int cantBytes;
	if (requestedBytes == 0){
		read_1_arg.bytes = requestedBytes;
		result_1 = read_1(&read_1_arg, clnt);
		cantBytes = result_1->data.data_len;
	}else{
		cantBytes = requestedBytes;
	}
	char * patz = malloc(512);
	strcpy(patz, "./client_filesystem/");
	strcat(patz, fname);
	FILE * fd = fopen(patz,"ab+");
	printf("Haciendo llamado RPC para lectura\n");
	while(cantBytes - cantRead > 0 ){
		if (cantBytes - cantRead < PKG_SIZE){
			printf("<===== Ultima lectura. Se leeran %d bytes ====>\n", (cantBytes - cantRead));
			read_1_arg.bytes = cantBytes - cantRead;			
		}else{
			printf("<===== Leyendo ====>\n" );
			read_1_arg.bytes = PKG_SIZE;
		}
		result_1 = read_1(&read_1_arg, clnt);
		cantRead += result_1->data.data_len;
		read_1_arg.pos += result_1->data.data_len;
		fwrite(result_1->data.data_val,1,cantRead,fd);
	}
	
	if (result_1 == (ftp_file *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
	fclose(fd);


#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void
write_ftp_server_1(char *host, char * fname, int cantBytes, char * buffer)
{
	printf("Comenzando llamado RPC para escritura\n");
	
	CLIENT *clnt;
	int  *result_2;
	ftp_file  write_1_arg;

	clnt = clnt_create (host, FTP_PROG, FTP_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	write_1_arg.name = fname;
	write_1_arg.data.data_val = buffer;
	write_1_arg.data.data_len = cantBytes;
	printf("Haciendo llamado RPC para escritura\n");
	result_2 = write_1(&write_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}printf("Creando archivo \n");

	clnt_destroy (clnt);
}








int
main (int argc, char *argv[])
{
	char *host;
	char * method;
	char * fname;
	int cantBytes;
	host = argv[1];
	method = argv[2];
	fname = argv[3];
	cantBytes = atoi(argv[4]);
	if (method[0] == 'r'){
		if (argc < 6){
			fprintf(stderr, "Error faltan argumentos para lectura\n");
		}
		int pos;
		pos = atoi(argv[5]);
		printf("Enviando pedido de lectura\n");
		read_ftp_server_1(host, fname, cantBytes, pos);

	}else if(method[0] == 'w'){
		
		if (argc < 6){
			fprintf(stderr, "Error faltan argumentos para escritura\n");
		}
		printf("Enviando pedido de escritura\n");
		char * buffer;
		buffer = argv[5];
		write_ftp_server_1(host, fname, cantBytes, buffer);

	}else{
			fprintf(stderr, "Error metodo incorrecto");
	}

exit (0);
}
