/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>


read_return *
leer_1_svc(void *argp, struct svc_req *rqstp)
{
	static read_return  result;
	char * filename = argp->filename;
    int pos = argp->pos;
    int cantBytes = argp->cantBytes;
    char * path = malloc(sizeof(char)*(strlen("./file_system_servidor/") + strlen(filename));
    strcpy(path, "./file_system_servidor/");
    strcat(path, filename);
    fopen(path, "r");
    

	return &result;
}

int *
escribir_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
