/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"
#define DATA_SIZE UINT_MAX

bool_t
xdr_ftp_file (XDR *xdrs, ftp_file *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 512))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->checksum))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ftp_req (XDR *xdrs, ftp_req *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 512))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->bytes))
		 return FALSE;
	return TRUE;
}
