/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"

bool_t
xdr_read_args (XDR *xdrs, read_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantBytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_result (XDR *xdrs, read_result *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->buffer_read, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_asked))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_read))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_args (XDR *xdrs, write_args *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->name, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->buffer, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
