/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"


void
srv_ftp_1(char *host)
{
	CLIENT *clnt;
	read_result  *result_1;
	read_args  leer_1_arg;
	int  *result_2;
	write_args  escribir_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SRV_FTP, FTP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = leer_1(&leer_1_arg, clnt);
	if (result_1 == (read_result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = escribir_1(&escribir_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	srv_ftp_1 (host);
exit (0);
}
