/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"
#include <stdio.h>

void
read_ftp_server_1(char *host, char * fname, int cantBytes, int pos)
{
	CLIENT *clnt;
	read_return  *result_1;
	read_args leer_1_arg;
	leer_1_arg.filename = fname;
	leer_1_arg.cantBytes = cantBytes;
	leer_1_arg.pos = pos;

#ifndef	DEBUG
	clnt = clnt_create (host, FTP_SERVER, FTP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = leer_1(&leer_1_arg, clnt);
	printf("%s\n", result_1->buffer_read);
	if (result_1 == (read_return *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
write_ftp_server_1(char *host, char * fname, int cantBytes, char * buffer)
{
	CLIENT *clnt;
	int  *result_2;
	write_args escribir_1_arg;
	escribir_1_arg.filename = fname;
	escribir_1_arg.buffer = buffer;
	escribir_1_arg.cantBytes = cantBytes;
#ifndef	DEBUG
	clnt = clnt_create (host, FTP_SERVER, FTP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_2 = escribir_1(&escribir_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	char * method;
	char * fname;
	int cantBytes;
	host = argv[1];
	method = argv[2];
	fname = argv[3];
	cantBytes = atoi(argv[4]);
	if (method[0] = 'r'){
		if (argc < 6){
			fprintf(stderr, "Error faltan argumentos para lectura");
		}
		int pos;
		pos = atoi(argv[5]);
		read_ftp_server_1(host, fname, cantBytes, pos);
	}else if(method[0] = 'w'){
		if (argc < 6){
			fprintf(stderr, "Error faltan argumentos para escritura");
		}
		char * buffer;
		buffer = argv[5];
		write_ftp_server_1(host, fname, cantBytes, buffer);
	}else{
			fprintf(stderr, "Error metodo incorrecto");
	}

exit (0);
}

