/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftp.h"

bool_t
xdr_file (XDR *xdrs, file *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buffer (XDR *xdrs, buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 100))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_args (XDR *xdrs, read_args *objp)
{
	register int32_t *buf;

	 if (!xdr_file (xdrs, &objp->filename))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantBytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_write_args (XDR *xdrs, write_args *objp)
{
	register int32_t *buf;

	 if (!xdr_file (xdrs, &objp->filename))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cantBytes))
		 return FALSE;
	 if (!xdr_buffer (xdrs, &objp->buffer_write))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_read_return (XDR *xdrs, read_return *objp)
{
	register int32_t *buf;

	 if (!xdr_buffer (xdrs, &objp->buffer_read))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_asked))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cant_read))
		 return FALSE;
	return TRUE;
}
