/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ftp.h"


void
ftp_server_1(char *host, char *src_name, int pos, int cantBytes)
{
	CLIENT *clnt;
	ftp_file  *src_file;
	ftp_req  request;

	clnt = clnt_create (host, FTP_SERVER, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

  	request.name = src_name;
  	request.pos = pos;
	request.length = (cantBytes == 0) ? 512 : cantBytes;

	src_file = read_file_1(&request, clnt);
	if (src_file == (ftp_file *) NULL) 
		clnt_perror (clnt, "call failed");

  	FILE* f = fopen("dest_name", "wb");
  	printf("\n Writing to %s", "dest_name");
  	printf("\n datalen es %d", src_file->data.data_len);
	
	if (cantBytes == 0){
		request.pos = 0; //Si se pide todo el archivo,
		while(src_file->data.data_len){
			fseek(f, request.pos, SEEK_SET);
			request.pos += fwrite(src_file->data.data_val, 1, src_file->data.data_len, f);
			src_file = read_file_1(&request, clnt);
			if (src_file == (ftp_file *) NULL) 
				clnt_perror (clnt, "call failed");
  		}
	}
	else{
		fseek(f, 0, SEEK_SET);
		request.pos += fwrite(src_file->data.data_val, 1, src_file->data.data_len, f);
		int bytesRead = src_file->data.data_len;
		if (bytesRead < cantBytes){
			while(src_file->data.data_len){    
				src_file = read_file_1(&request, clnt);
				if (src_file == (ftp_file *) NULL) 
					clnt_perror (clnt, "call failed");
					printf("\n datalen es %d", src_file->data.data_len);
				fseek(f, bytesRead, SEEK_SET);
				request.pos += fwrite(src_file->data.data_val, 1, src_file->data.data_len, f);
				bytesRead += src_file->data.data_len;
			}
		}
	}
  	
  fclose(f);
  printf("\n %lu bytes written.", request.pos);

  clnt_destroy (clnt);
}

void
ftp_server_2(char *host, char *src_name, char *dest_name)
{
	CLIENT *clnt;
	ftp_file  src_file;
	int*  write_result;

	clnt = clnt_create (host, FTP_SERVER, VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

  src_file.name = dest_name;
  src_file.pos = 0;
  src_file.data.data_val = malloc(sizeof(char)*512);
  FILE* f = fopen(src_name, "rb");
  printf("\n Reading file %s", src_name);
  while(src_file.data.data_len = fread(src_file.data.data_val, 1, 512, f)){
	  write_result = write_file_1(&src_file, clnt);
	  if (write_result == (int *) NULL) 
		  clnt_perror (clnt, "call failed");
    src_file.pos += src_file.data.data_len;
    fseek(f, src_file.pos, SEEK_SET);
  }

  fclose(f);
  printf("\n %lu bytes sent.", src_file.pos);

  clnt_destroy (clnt);
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
  if(strcmp(argv[2], "read") == 0)
	  ftp_server_1 (host, argv[3], atoi(argv[4]), atoi(argv[5]));
  else if(strcmp(argv[2], "write") == 0)
    ftp_server_2 (host, argv[3], argv[4]);
  else
    printf("\n Unknown command.");
  printf("\n");
  exit (0);
}
